mainserver:
  image: nicholasjackson/docker-testing
  ports:
    - "8001:8001"
  links:
    - helloworldserver:helloworldserver
    - mailserver:mailserver
    - consul:consul
helloworldserver:
  image: nicholasjackson/mimic-docker
  ports:
    - "11988:11988"
mailserver:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"
    - "1025:1025"
consul:
  image: progrium/consul
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  hostname: node1
  command: "-server -bootstrap -ui-dir /ui"
